version: '3.8'

services:
  frontend:
    image: airbnb-frontend:1.0
    ports:
      - "80:80"
    networks:
      - my_network

  backend:
    image: airbnb-backend:1.0
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
